OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET CL8MSWIN1251 
 TRUNCATE INTO TABLE DF.UT_SAP_HR_DEP_NAME
 FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'
 TRAILING NULLCOLS
 (        DEP, LANG, DEP_NAME   )
