OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET CL8MSWIN1251 
 TRUNCATE INTO TABLE DF.UT_SAP_HR_OFFICER
 FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'
 TRAILING NULLCOLS
 (OFFICER_NUM,
  STATUS,
  DEP_PREV,
  DEP,
  JOB_PREV,
  JOB,
  TIN,
  EMPLOYMENT_STATUS,
  RANG,
  REGION,
  REGION_NAME,
  POST_CODE,
  CITY_NAME,
  STR_NAME,
  HOUSE_NO,
  DATE_B "TO_DATE(:DATE_B, 'DD.MM.YYYY')",
  DATE_E "TO_DATE(:DATE_E, 'DD.MM.YYYY')",
  E_MAILE
 )
 
 
