OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET CL8MSWIN1251 
 TRUNCATE INTO TABLE DF.UT_SAP_HR_OFFICER_NAME
 FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'
 TRAILING NULLCOLS
 (       OFFICER_NUM,
  LANG,
  SECOND_NAME,
  FIRST_NAME,
  MIDDLE_NAME
 )
 
 
