OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET CL8MSWIN1251 
 TRUNCATE INTO TABLE DF.UT_SAP_HR_PHONE_PERS
 FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'
 TRAILING NULLCOLS
 (       OFFICER_NUM, 
         COL1,
	 PHONE
 )
