LOAD DATA
CHARACTERSET CL8MSWIN1251 
 TRUNCATE INTO TABLE DF.UT_SAP_HR_PERS_STRUCT
 FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'
 TRAILING NULLCOLS
 (ENAME,
  PERNR,
  USRID,
  PLANS_ID,
  PLANS,  
  ERGRU,
  ORGEH_ID,
  ORGEH,
  HTEXT_V_ID,
  HTEXT_V,
  HTEXT_ID,
  HTEXT,
  WERKS_ID,
  WERKS,
  REGION_ID,
  REGION,
  STEXT	
 )
