
INSERT
INTO DF.DOC_DIC_GR_RECIPIENTS
  (
    ID_DIC_GR_RECIT,
    NAME
  )
  VALUES
  (
    7,
    'По должности'
  );
  
  ;
   
  
 CREATE TABLE DF.DIC_FAV_EMP
  (
    ID_FAV_REC      NUMBER CONSTRAINT NNC_ID_FAV_REC NOT NULL ,
    ID_FAV_GR_EMP   NUMBER NOT NULL ,
    ID_DIC_GR_RECIT NUMBER NOT NULL ,
    VALUE_ID        INTEGER
  ) ;
COMMENT ON TABLE DF.DIC_FAV_EMP
IS
  'Справочник любимых групп сотрудников' ;
  COMMENT ON COLUMN DF.DIC_FAV_EMP.VALUE_ID
IS
  'ID значения из соответствующего справочника' ;
  ALTER TABLE DF.DIC_FAV_EMP ADD CONSTRAINT DIC_FAV_EMP_PK PRIMARY KEY ( ID_FAV_REC ) ;
  
  
  
  
  CREATE TABLE DF.DIC_FAV_GR_EMP
    (
      ID_FAV_GR_EMP NUMBER CONSTRAINT NNC_ID_FAV_GR_EMP NOT NULL ,
      NAME          VARCHAR2 (100) ,
      OWN_OFFICER_NUM   NUMBER
    ) ;
  COMMENT ON TABLE DF.DIC_FAV_GR_EMP
IS
  'Спр. групп получателей (например: По рангам, по облостям, по направлениям)' ;
  ALTER TABLE DF.DIC_FAV_GR_EMP ADD CONSTRAINT DIC_FAV_GR_EMP_PK PRIMARY KEY ( ID_FAV_GR_EMP ) ;
  ALTER TABLE DF.DIC_FAV_EMP ADD CONSTRAINT D_FAV_EMP_DIC_GR_RECIP_FK FOREIGN KEY ( ID_DIC_GR_RECIT ) REFERENCES DF.DOC_DIC_GR_RECIPIENTS ( ID_DIC_GR_RECIT ) ;
  ALTER TABLE DF.DIC_FAV_EMP ADD CONSTRAINT D_FAV_EMP_D_FAV_GR_EMP_FK FOREIGN KEY ( ID_FAV_GR_EMP ) REFERENCES DF.DIC_FAV_GR_EMP ( ID_FAV_GR_EMP ) ;
CREATE SEQUENCE DF.DIC_FAV_EMP_ID_FAV_REC_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER DF.DIC_FAV_EMP_ID_FAV_REC_TRG BEFORE
  INSERT ON DF.DIC_FAV_EMP FOR EACH ROW WHEN (NEW.ID_FAV_REC IS NULL) BEGIN :NEW.ID_FAV_REC := DF.DIC_FAV_EMP_ID_FAV_REC_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE DF.DIC_FAV_GR_EMP_ID_FAV_GR_EMP START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER DF.DIC_FAV_GR_EMP_ID_FAV_GR_EMP BEFORE
  INSERT ON DF.DIC_FAV_GR_EMP FOR EACH ROW WHEN (NEW.ID_FAV_GR_EMP IS NULL) BEGIN :NEW.ID_FAV_GR_EMP := DF.DIC_FAV_GR_EMP_ID_FAV_GR_EMP.NEXTVAL;
END;
/
