SELECT 
DC.ID_DOC,	 ID_CORR AS CORR_TYPE_FULL,	
CODE,	NAME,	DATE_IN,
ID_STATUS,	NOTE,	DATE_PUB,	DATE_EFFECTIVE,
DATE_EXPIRE,	IS_CLOSED,	SIGN_OFFICER_NUM,	ID_DEP_OWNER,
ID_DOC_ADD,	ID_ORDER_TYPE,	DATE_SH_UPD,
DATE_LAST_UPD,	ORD_VERSION,	ORD_LEVEL,	ID_SCOUPE	,ID_RISK,
ID_EMP_AUTHOR AS ID_AUTHOR

FROM DF.DOC_CARD DC,
           DF.DOC_CARD_ADD DCA
WHERE DC.ID_DOC = DCA.ID_DOC (+)

AND DC.id_doc BETWEEN 5502 AND 6167
