
alter table DF.DOC_EMP_ACCEPTING
  add (REQUESTER_OFFICER_NUM NUMBER);
  
alter table DF.DOC_FLOW
 add (DATE_S DATE  );
 
 
 CREATE TABLE DF.DIC_FAV_EMP
  (
    ID_FAV_REC      NUMBER CONSTRAINT NNC_ID_FAV_REC NOT NULL ,
    ID_FAV_GR_EMP   NUMBER NOT NULL ,
    ID_DIC_GR_RECIT NUMBER NOT NULL ,
    VALUE_ID        INTEGER
  ) ;
COMMENT ON TABLE DF.DIC_FAV_EMP
IS
  'Справочник любимых групп сотрудников' ;
  COMMENT ON COLUMN DF.DIC_FAV_EMP.VALUE_ID
IS
  'ID значения из соответствующего справочника' ;
  ALTER TABLE DF.DIC_FAV_EMP ADD CONSTRAINT DIC_FAV_EMP_PK PRIMARY KEY ( ID_FAV_REC ) ;
  
  
  
  
  CREATE TABLE DF.DIC_FAV_GR_EMP
    (
      ID_FAV_GR_EMP NUMBER CONSTRAINT NNC_ID_FAV_GR_EMP NOT NULL ,
      NAME          VARCHAR2 (100) ,
      OWN_OFFICER_NUM   NUMBER
    ) ;
  COMMENT ON TABLE DF.DIC_FAV_GR_EMP
IS
  'Спр. групп получателей (например: По рангам, по облостям, по направлениям)' ;
  ALTER TABLE DF.DIC_FAV_GR_EMP ADD CONSTRAINT DIC_FAV_GR_EMP_PK PRIMARY KEY ( ID_FAV_GR_EMP ) ;
  ALTER TABLE DF.DIC_FAV_EMP ADD CONSTRAINT D_FAV_EMP_DIC_GR_RECIP_FK FOREIGN KEY ( ID_DIC_GR_RECIT ) REFERENCES DF.DOC_DIC_GR_RECIPIENTS ( ID_DIC_GR_RECIT ) ;
  ALTER TABLE DF.DIC_FAV_EMP ADD CONSTRAINT D_FAV_EMP_D_FAV_GR_EMP_FK FOREIGN KEY ( ID_FAV_GR_EMP ) REFERENCES DF.DIC_FAV_GR_EMP ( ID_FAV_GR_EMP ) ;
CREATE SEQUENCE DF.DIC_FAV_EMP_ID_FAV_REC_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER DF.DIC_FAV_EMP_ID_FAV_REC_TRG BEFORE
  INSERT ON DF.DIC_FAV_EMP FOR EACH ROW WHEN (NEW.ID_FAV_REC IS NULL) BEGIN :NEW.ID_FAV_REC := DF.DIC_FAV_EMP_ID_FAV_REC_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE DF.DIC_FAV_GR_EMP_ID_FAV_GR_EMP START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER DF.DIC_FAV_GR_EMP_ID_FAV_GR_EMP BEFORE
  INSERT ON DF.DIC_FAV_GR_EMP FOR EACH ROW WHEN (NEW.ID_FAV_GR_EMP IS NULL) BEGIN :NEW.ID_FAV_GR_EMP := DF.DIC_FAV_GR_EMP_ID_FAV_GR_EMP.NEXTVAL;
END;
/

CREATE TABLE DF.DOC_EXEC_EMP_ST
  (
    ID_EXEC_EMP_ST NUMBER (10) NOT NULL ,
    ID_DOC         NUMBER NOT NULL ,
    OFFICER_NUM    NUMBER NOT NULL ,
    DTA            DATE ,
    EXEC_ST        NUMBER (1) ,
    NOTE           VARCHAR2(255)
  ) ;
COMMENT ON TABLE DF.DOC_EXEC_EMP_ST
IS
  'Статус исполнения' ;
  ALTER TABLE DF.DOC_EXEC_EMP_ST ADD CONSTRAINT DOC_EXEC_EMP_ST_PK PRIMARY KEY ( ID_EXEC_EMP_ST ) ;
  ALTER TABLE DF.DOC_EXEC_EMP_ST ADD CONSTRAINT DOC_EXEC_EMP_ST_DOC_CARD_FK FOREIGN KEY ( ID_DOC ) REFERENCES DF.DOC_CARD ( ID_DOC ) ;
CREATE SEQUENCE DF.DOC_EXEC_EMP_ST_ID_EXEC_EMP_ST START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER DF.DOC_EXEC_EMP_ST_ID_EXEC_EMP_ST BEFORE
  INSERT ON DF.DOC_EXEC_EMP_ST FOR EACH ROW WHEN (NEW.ID_EXEC_EMP_ST IS NULL) BEGIN :NEW.ID_EXEC_EMP_ST := DF.DOC_EXEC_EMP_ST_ID_EXEC_EMP_ST.NEXTVAL;
END;


/* SAP HR UPLOADING TABLES*/

--DROP TABLE  DF.UT_SAP_HR_ABSENT_CAT ;


CREATE TABLE DF.UT_SAP_HR_ABSENT_CAT  (
    AWART VARCHAR2(4), 
    ABWTXT VARCHAR2 (255)
);

--DROP TABLE DF.SAP_HR_ABSENT_CAT;

CREATE TABLE DF.SAP_HR_ABSENT_CAT  AS
 SELECT * FROM DF.UT_SAP_HR_ABSENT_CAT;
 
 --DROP TABLE DF.UT_WEEKEND;
 
 CREATE TABLE DF.UT_WEEKEND (
  DTA DATE,
  IS_WEEKEND NUMBER(1)
 );


 --DROP TABLE DF.WEEKEND;
 
CREATE TABLE DF.WEEKEND AS
 SELECT * FROM DF.UT_WEEKEND ;
 
 --DROP TABLE  DF.UT_SAP_HR_PERS_ABSENT;
 
 CREATE TABLE DF.UT_SAP_HR_PERS_ABSENT (
    PERSNO NUMBER, 
    AWART VARCHAR2(4), 
    ABWTXT VARCHAR2 (255),
    BEGDA DATE,
    ENDDA DATE    
 ); 
 
 --DROP TABLE  DF.SAP_HR_PERS_ABSENT;
 
 CREATE TABLE DF.SAP_HR_PERS_ABSENT  AS
 SELECT * FROM DF.UT_SAP_HR_PERS_ABSENT ;
 
 
 ALTER TABLE DF.UT_SAP_HR_PERS_STRUCT
 ADD (STEXT VARCHAR2 (256));
 
 ALTER TABLE DF.SAP_HR_PERS_STRUCT
  ADD (STEXT VARCHAR2 (256));